# puts "What state do you live in? Use the state's abbreviation."
# state=gets.chomp.downcase
# def state_chooser(state)
# if state=="al"
#   @rec = "You live in Alabama. A good pet shelter in your state is the Montgomery Humane Society."
#   elsif state=="ak"
#     @rec = "You live in Alaska. A good pet shelter in your state is the Gastineau Humane Society."
#   elsif state=="az"
#     @rec = "You live in Arizona. A good pet shelter in your state is the Halo Animal Rescue."
#   elsif state=="ar"
#     @rec = "You live in Arkansas. A good pet shelter in your state is the Humane Society of Pulaski County."
#   elsif state=="ca"
#     @rec = "You live in California. A good pet shelter in your state is the LA Animal Services."
#   elsif state=="co"
#     @rec = "You live in Colorado. A good pet shelter in your state is the Denver Animal Shelter."
#   elsif state=="ct"
#     @rec =  "You live in Connecticut. A good pet shelter in your state is Friends of the New Haven Animal Shelter."
#   elsif state=="de"
#     @rec = "You live in Delaware. A good pet shelter in your state is the Faithful Friends Animal Society."
#   elsif state=="fl"
#     @rec = "You live in Florida. A good pet shelter in your state is the Humane Society of Greater Miami."
#   elsif state=="ga"
#     @rec = "You live in Georgia. A good pet shelter in your state is the Atlanta Humane Society."
#   elsif state=="hi"
#     @rec = "You live in Hawaii. A good pet shelter in your state is the Hawaiian Humane Society."
#   elsif state=="id"
#     @rec = "You live in Idaho. A good pet shelter in your state is the Idaho Humane Society."
#   elsif state=="il"
#     @rec = "You live in Illinois. A good pet shelter in your state is the Animal Protective League."
#   elsif state=="in"
#     @rec = "You live in Indiana. A good pet shelter in your state is IndyHumane - Humane Society of Indianapolis."
#   elsif state=="ia"
#     @rec = "You live in Iowa. A good pet shelter in your state is the Animal Rescue League of Iowa."
#   elsif state=="ks"
#     @rec = "You live in Kansas. A good pet shelter in your state is the Helping Hands Humane Society."
#   elsif state=="ky"
#     @rec = "You live in Kentucky. A good pet shelter in your state is the L.I.F.E. House for Animals."
#   elsif state=="la"
#     @rec = "You live in Louisiana. A good pet shelter in your state is the Companion Animal Alliance of Baton Rouge."
#   elsif state=="me"
#     @rec = "You live in Maine. A good pet shelter in your state is the Kennebec Valley Humane Society."
#   elsif state=="md"
#     @rec = "You live in Maryland. A good pet shelter in your state is the AACSPCA."
#   elsif state=="ma"
#     @rec = "You live in Massachusetts. A good pet shelter in your state is the Northeast Animal Shelter."
#   elsif state=="mi"
#     @rec = "You live in Michigan. A good pet shelter in your state is the Capital Area Humane Society."
#   elsif state=="mn"
#     @rec = "You live in Minnesota. A good pet shelter in your state is the Animal Humane Society."
#   elsif state=="ms"
#     @rec = "You live in Mississippi. A good pet shelter in your state is the Mississippi Animal Rescue League."
#   elsif state=="mo"
#     @rec = "You live in Missouri. A good pet shelter in your state is the Humane Society of Missouri."
#   elsif state=="mt"
#     @rec = "You live in Montana. A good pet shelter in your state is the Humane Society of Western Montana."
#   elsif state=="ne"
#     @rec = "You live in Nebraska. A good pet shelter in your state is the Capital Humane Society."
#   elsif state=="nv"
#     @rec = "You live in Nevada. A good pet shelter in your state is the Nevada Humane Society."
#   elsif state=="nh"
#     @rec = "You live in New Hampshire. A good pet shelter in your state is the Pope Memorial SPCA."
#   elsif state=="nj"
#     @rec = "You live in New Jersey. A good pet shelter in your state is the NJSPCA."
#   elsif state=="nm"
#     @rec = "You live in New Mexico. A good pet shelter in your state is the Santa Fe Animal Shelter & Humane Society."
#   elsif state=="ny"
#     @rec = "You live in New York. A good pet shelter in your state is the Animal Care Center of NYC."
#   elsif state=="nc"
#     @rec = "You live in North Carolina. A good pet shelter in your state is the Wake County Animal Shelter."
#   elsif state=="nd"
#     @rec = "You live in North Dakota. A good pet shelter in your state is the Central Dakota Humane Society."
#   elsif state=="oh"
#     @rec = "You live in Ohio. A good pet shelter in your state is the CHA Animal Shelter."
#   elsif state=="ok"
#     @rec = "You live in Oklahoma. A good pet shelter in your state is OKC Animal Welfare."
#   elsif state=="or"
#     @rec = "You live in Oregon. A good pet shelter in your state is the Oregon Humane Society."
#   elsif state=="pa"
#     @rec = "You live in Pennsylvania. A good pet shelter in your state is the Humane Society of Harrisburg Area."
#   elsif state=="ri"
#     @rec = "You live in Rhode Island. A good pet shelter in your state is Animal Rescue Rhode Island."
#   elsif state=="sc"
#     @rec = "You live in South Carolina. A good pet shelter in your state is Pawmetto Lifeline."
#   elsif state=="sd"
#     @rec = "You live in South Dakota. A good pet shelter in your state is the Hopeless to Homes Animal Rescue."
#   elsif state=="tn"
#     @rec = "You live in Tennessee. A good pet shelter in your state is Nashville Humane."
#   elsif state=="tx"
#     @rec = "You live in Texas. A good pet shelter in your state is the Houston SPCA."
#   elsif state=="ut"
#     @rec = "You live in Utah. A good pet shelter in your state is the Humane Society of Utah."
#   elsif state=="vt"
#     @rec = "You live in Vermont. A good pet shelter in your state is the Central Vermont Humane Society."
#   elsif state=="va"
#     @rec = "You live in Virginia. A good pet shelter in your state is the Richmond SPCA."
#   elsif state=="wa"
#     @rec = "You live in Washington. A good pet shelter in your state is Joint Animal Services."
#   elsif state=="wv"
#     @rec = "You live in West Virginia. A good pet shelter in your state is the Charlston Animal Society."
#   elsif state=="wi"
#     @rec =  "You live in Wisconsin. A good pet shelter in your state is the Wisconsin Humane Society."
#   elsif state=="wy"
#     @rec =  "You live in Wyoming. A good pet shelter in your state is the Black Dog Animal Rescue."
#   else
#     @rec =  "Sorry, we don't recognize that state. We only accept states in America. Make sure you use the state's abbreviation. For example, mn for Minnesota. Try again."
#   end
# end 